### PR TITLE
add source editing feature

### PR DESCRIPTION
**Pull request by hkashlan**
add source editing to this will solve issue #18

### CODE REVIEW

**Comment by hkashlan** [comment]
@roslovets 
could you please check my PR.

**Review by gokaybiz — APPROVED** [review]

**Comment by gokaybiz** [comment]
Hi @hkashlan,
When I tried with strapi-plugin-ckeditor5 plugin, It's break few things.
Like media library doesn't work. And in source mode, there is no scrollbar. 
It's probably associated with ckeditor5-core version. I don't know.

Could you check?

**Comment by hkashlan** [comment]
I will sorry for delay but I am sick this week :(

**Comment by hkashlan** [comment]
@gokaybiz 
thank you for review the PR,

- for scroll issue: in live demo there is no scrolling so I don't think I broke it

https://roslovets-inc.github.io/ckeditor5-build-strapi-wysiwyg/

- media library : it will not work in demo it should be inside the strapi, 
how did you test it is not working? I don't know how to test it in demo

**Comment by roslovets** [comment]
Seems like `GeneralHtmlSupport` is experimental feature. It works bad even on [CKEditor site](https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html). so I don't think it's a good idea to introduce it now.

**Comment by roslovets** [comment]
> Hi @hkashlan, When I tried with strapi-plugin-ckeditor5 plugin, It's break few things. Like media library doesn't work. And in source mode, there is no scrollbar. It's probably associated with ckeditor5-core version. I don't know.
> 
> Could you check?

In CKEditor >=29.0.0 Media Library buttons fails to insert image (tested in Strapi). In 29.0.0 lots of breaking changes were introduced, please check [this](https://github.com/ckeditor/ckeditor5/releases/tag/v29.0.0) out.

**Pull request merged**
