### PR TITLE
Update ckeditor5 and install SourceEditing plugin

### PR DESCRIPTION
**Pull request by AndColla**

### CODE REVIEW

**Comment by roslovets** [comment]
Thanks, but please make sure, that upgrading of CKEditor will not break Media Upload button: https://github.com/Roslovets-Inc/ckeditor5-build-strapi-wysiwyg/pull/20#issuecomment-967754318

**Comment by schwarzi33** [comment]
Hey @AndColla! Do you have any updates regarding this feature? I would really appreciate the SourceEditing functionality in Strapi

**Comment by roslovets** [comment]
I will do this, thanks. Unfortunately this branch cannot be merged directly due to conflicts.

**Comment by roslovets** [comment]
I will do this, thanks. Unfortunately this branch cannot be merged directly due to conflicts.

**Pull request closed without merging**
